### PR TITLE
Use prepend instead to ensure PATH is properly setup for winpty.

### PR DESCRIPTION
**Pull request by yclian**

### CODE REVIEW

**Comment by yclian** [comment]
This should fix a few problems appeared in a few threads, e.g. https://github.com/tiangolo/babun-docker/issues/5.

**Comment by tiangolo** [comment]
@yclian Sorry for the delay. 

I was reading from your comment in https://github.com/tiangolo/babun-docker/issues/5#issuecomment-275862059 , Were you having a "`winpty` not found" error? Why would prepending it to the `PATH` fix the problem? 

As I understand, if it is in the `PATH` variable, it should still work. The problem that could arise from not prepending it to the `PATH` would be if there was another "findable" binary with the same name, before in the `PATH`, that didn't work... but that's not the case as I understand...

Can you help me understand that?

**Comment by murray02** [comment]
SUGGESTION: 

Add -q --no-check-certificate to the wget line too. I have been having this issue, for just about FOREVER.....

Prepending the PATH and fixing the wget solved my issue. 

If not, I can fork and pull on another PR.

**Comment by murray02** [comment]
I have created a PR for all of the issues I found.

https://github.com/tiangolo/babun-docker/pull/34

**Comment by tiangolo** [comment]
This should be fixed in the latest commits. With @murray02 's PR.

**Pull request closed without merging**
