### PR TITLE
Handle command exit code when running within winpty

### PR DESCRIPTION
**Pull request by ptisserand**
This patch provide support to retrieve command exit code when docker is run under winpty.

### CODE REVIEW

**Comment by tiangolo** [comment]
Thanks for this!

---

I'm testing it, but when I run:

```bash
docker asdf
```

and then:

```bash
echo $?
```

I get `0`

But if I do the same in Linux:

```bash
docker asdf
# docker: 'asdf' is not a docker command.
# See 'docker --help'

echo $?
# 1
```

I get `1` as the status code. I double checked that I was using your patched version. But still, it seems I'm not getting the status code as expected.

**Comment by ptisserand** [comment]
Thanks for feedback, sorry about this issue with your test case.
I didn't notice it since I was mainly working on running docker within winpty.

I have pushed a fix (349a2d392697b12c59e4f3a074f1fc2dc1d81a5e) which fix this issue on my side.
Please note it's not clear for me why babun bash is using `pipestatus` (**zsh**) instead of `PIPESTATUS` (**bash**) variable
```bash
 { ~ }  » docker adsf                                                                            
docker: 'adsf' is not a docker command.
See 'docker --help'
{ ~ }  » echo $?                                                                              
1
```
```bash
{ ~ }  » docker run --rm -t -i ubuntu /bin/not_here                                            
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
-- babun-docker: Using winpty
C:\Program Files\Docker\Docker\Resources\bin\docker: Error response from daemon: oci runtime error:
container_linux.go:265: starting container process caused "exec: \"/bin/not_here\": stat /bin/not_he
re: no such file or directory".
{ ~ }  » echo $?                                                                          
127
```
```bash
{ ~ }  » docker pull not_found                                                                  
Using default tag: latest
Error response from daemon: pull access denied for not_found, repository does not exist or may require 'docker login'
{ ~ }  » echo $?                                                                              
1
```

**Comment by ptisserand** [comment]
Hi @tiangolo , did you check my updated pull request ?

Regards,
Patrice

**Comment by tiangolo** [comment]
Great! Thanks! :tada:

**Pull request merged**
